baseURL: https://iwakunibob.github.io/learnhugo0/ 
# http://localhost/
# 
# disable taxonomy pages (defaults catagories and tags)
disableKinds:
- taxonomy
- taxonomyTerm
languageCode: en-us
# relativeURLs: true
title: My Learning Hugo Site
# alternative copyright company
copyright: Robert Laurie
# controls number of pages displayed on list pages
paginate: 3
# controls summary length on list pages
summaryLength: 7
markup: 
  goldmark:
    renderer:
      unsafe: true

# Menu Links via config file
menu:
  main:
  - name: Github
    url: https://www.github.com
    weight: 90
    params:
      blank: true
  - name: Google
    url: https://www.google.com
    weight: 100
    params:
      blank: true